spring.application.name: gateway_13200
server.port: 13200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:13100/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: false
            maxAge: 3600
